### ISSUE TITLE
What happens when dayjs.tz.guess() can't guess the timezone? Does it return an empty string?

### ISSUE THREAD

**Issue by charlielevine** [dayjs/dayjs-website#40] opened 2021-03-09 23:57 UTC

**Comment by iamkun** [comment] 2021-03-10 04:58
a reproduction demo please

**Comment by iamkun** [comment] 2021-06-02 07:46
I'll close this since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Closed by iamkun** 2021-06-02 07:46 UTC
